# Generated by Django 3.2 on 2023-05-09 11:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Put a Title')),
                ('short_description', models.TextField(max_length=500)),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('blog_image', models.ImageField(upload_to='blog_images', verbose_name='Image')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value1', models.PositiveIntegerField()),
                ('value2', models.PositiveIntegerField()),
                ('value3', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_contact', models.CharField(max_length=250)),
                ('company_location', models.TextField(verbose_name='Company Address')),
                ('business_purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('c_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.PositiveIntegerField()),
                ('value2', models.PositiveIntegerField()),
                ('value3', models.PositiveIntegerField()),
                ('business_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgd_consultancy_app.businessplan')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgd_consultancy_app.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgd_consultancy_app.location')),
            ],
        ),
    ]
