# Generated by Django 3.2 on 2023-07-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd_consultancy_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='package_information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
