# Generated by Django 3.2 on 2023-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd_consultancy_app', '0003_companyinfo_package_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='package_information',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
