# Generated by Django 3.2 on 2023-08-19 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgd_consultancy_app', '0004_alter_companyinfo_package_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
