# Generated by Django 3.2 on 2023-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd_consultancy_app', '0007_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=250)),
            ],
        ),
    ]
