# Generated by Django 3.2 on 2023-08-26 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgd_consultancy_app', '0008_selectedpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedpackage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_app.user'),
            preserve_default=False,
        ),
    ]
