# Generated by Django 3.2 on 2023-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslpayment_app', '0002_auto_20230822_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
