# Generated by Django 3.2 on 2023-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslpayment_app', '0003_auto_20230822_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
